emit("\t.section\t__TEXT,__text,regular,pure_instructions");
emit("\t.build_version macos, 13, 0\tsdk_version 13, 0");
emit("\t.globl\t_allocate                       ; -- Begin function allocate");
emit("\t.p2align\t2");
emit("_allocate:                              ; @allocate");
emit("; %bb.0:");
emit("\tsub\tsp, sp, #80");
emit("\tadrp\tx8, _free_list@PAGE");
emit("\tadd\tx8, x8, _free_list@PAGEOFF");
emit("\tadd\tx8, x8, #8");
emit("\tstr\tx8, [sp, #8]                    ; 8-byte Folded Spill");
emit("\tstr\tw0, [sp, #68]");
emit("\tldr\tw8, [sp, #68]");
emit("\tadd\tw8, w8, #8");
emit("\tstr\tw8, [sp, #68]");
emit("\tb\tLBB0_1");
emit("LBB0_1:                                 ; =>This Inner Loop Header: Depth=1");
emit("\tldr\tw8, [sp, #68]");
emit("\tmov\tw10, #8");
emit("\tsdiv\tw9, w8, w10");
emit("\tmul\tw9, w9, w10");
emit("\tsubs\tw8, w8, w9");
emit("\tcbz\tw8, LBB0_3");
emit("\tb\tLBB0_2");
emit("LBB0_2:                                 ;   in Loop: Header=BB0_1 Depth=1");
emit("\tldr\tw8, [sp, #68]");
emit("\tadd\tw8, w8, #1");
emit("\tstr\tw8, [sp, #68]");
emit("\tb\tLBB0_1");
emit("LBB0_3:");
emit("\tadrp\tx8, _free_list@PAGE");
emit("\tldr\tx8, [x8, _free_list@PAGEOFF]");
emit("\tcbnz\tx8, LBB0_5");
emit("\tb\tLBB0_4");
emit("LBB0_4:");
emit("\tldr\tx9, [sp, #8]                    ; 8-byte Folded Reload");
emit("\tadrp\tx8, _free_list@PAGE");
emit("\tstr\tx9, [x8, _free_list@PAGEOFF]");
emit("\tldr\tx9, [x8, _free_list@PAGEOFF]");
emit("\tmov\tw8, #49536");
emit("\tmovk\tw8, #124, lsl #16");
emit("\tstr\tw8, [x9]");
emit("\tb\tLBB0_5");
emit("LBB0_5:");
emit("\tadrp\tx8, _free_list@PAGE");
emit("\tldr\tx8, [x8, _free_list@PAGEOFF]");
emit("\tstr\tx8, [sp, #48]");
emit("\tldr\tx8, [sp, #48]");
emit("\tadd\tx8, x8, #8");
emit("\tstr\tx8, [sp, #40]");
emit("\tldr\tx8, [sp, #40]");
emit("\tldr\tx8, [x8]");
emit("\tcbnz\tx8, LBB0_9");
emit("\tb\tLBB0_6");
emit("LBB0_6:");
emit("\tldr\tw8, [sp, #68]");
emit("\tldr\tx9, [sp, #48]");
emit("\tldr\tw9, [x9]");
emit("\tsubs\tw8, w8, w9");
emit("\tb.gt\tLBB0_8");
emit("\tb\tLBB0_7");
emit("LBB0_7:");
emit("\tldr\tx8, [sp, #40]");
emit("\tstr\tx8, [sp, #56]");
emit("\tldr\tx8, [sp, #40]");
emit("\tldrsw\tx9, [sp, #68]");
emit("\tadd\tx9, x8, x9");
emit("\tadrp\tx8, _free_list@PAGE");
emit("\tstr\tx9, [x8, _free_list@PAGEOFF]");
emit("\tldr\tx9, [sp, #48]");
emit("\tldr\tw9, [x9]");
emit("\tstr\tw9, [sp, #36]");
emit("\tldr\tw9, [sp, #68]");
emit("\tldr\tx10, [sp, #48]");
emit("\tstr\tw9, [x10]");
emit("\tldr\tx8, [x8, _free_list@PAGEOFF]");
emit("\tstr\tx8, [sp, #48]");
emit("\tldr\tw8, [sp, #36]");
emit("\tldr\tw9, [sp, #68]");
emit("\tsubs\tw8, w8, w9");
emit("\tldr\tx9, [sp, #48]");
emit("\tstr\tw8, [x9]");
emit("\tldr\tx8, [sp, #56]");
emit("\tstr\tx8, [sp, #72]");
emit("\tb\tLBB0_27");
emit("LBB0_8:");
emit("                                        ; kill: def $x8 killed $xzr");
emit("\tstr\txzr, [sp, #72]");
emit("\tb\tLBB0_27");
emit("LBB0_9:");
emit("\tldr\tw8, [sp, #68]");
emit("\tldr\tx9, [sp, #48]");
emit("\tldr\tw9, [x9]");
emit("\tsubs\tw8, w8, w9");
emit("\tb.ge\tLBB0_11");
emit("\tb\tLBB0_10");
emit("LBB0_10:");
emit("\tldr\tx8, [sp, #40]");
emit("\tstr\tx8, [sp, #56]");
emit("\tldr\tx8, [sp, #40]");
emit("\tldrsw\tx9, [sp, #68]");
emit("\tadd\tx9, x8, x9");
emit("\tadrp\tx8, _free_list@PAGE");
emit("\tstr\tx9, [x8, _free_list@PAGEOFF]");
emit("\tldr\tx9, [sp, #48]");
emit("\tldr\tw9, [x9]");
emit("\tstr\tw9, [sp, #32]");
emit("\tldr\tw9, [sp, #68]");
emit("\tldr\tx10, [sp, #48]");
emit("\tstr\tw9, [x10]");
emit("\tldr\tx8, [x8, _free_list@PAGEOFF]");
emit("\tstr\tx8, [sp, #48]");
emit("\tldr\tw8, [sp, #32]");
emit("\tldr\tw9, [sp, #68]");
emit("\tsubs\tw8, w8, w9");
emit("\tldr\tx9, [sp, #48]");
emit("\tstr\tw8, [x9]");
emit("\tldr\tx8, [sp, #56]");
emit("\tstr\tx8, [sp, #72]");
emit("\tb\tLBB0_27");
emit("LBB0_11:");
emit("\tldr\tw8, [sp, #68]");
emit("\tldr\tx9, [sp, #48]");
emit("\tldr\tw9, [x9]");
emit("\tsubs\tw8, w8, w9");
emit("\tb.ne\tLBB0_13");
emit("\tb\tLBB0_12");
emit("LBB0_12:");
emit("\tldr\tx8, [sp, #40]");
emit("\tstr\tx8, [sp, #56]");
emit("\tldr\tx8, [sp, #40]");
emit("\tldrsw\tx9, [sp, #68]");
emit("\tadd\tx8, x8, x9");
emit("\tadrp\tx9, _free_list@PAGE");
emit("\tstr\tx8, [x9, _free_list@PAGEOFF]");
emit("\tldr\tx8, [sp, #56]");
emit("\tstr\tx8, [sp, #72]");
emit("\tb\tLBB0_27");
emit("LBB0_13:");
emit("\tldr\tx8, [sp, #40]");
emit("\tldr\tx8, [x8]");
emit("\tstr\tx8, [sp, #40]");
emit("\tb\tLBB0_14");
emit("LBB0_14:                                ; =>This Inner Loop Header: Depth=1");
emit("\tldr\tx8, [sp, #40]");
emit("\tldr\tx8, [x8]");
emit("\tmov\tw9, #0");
emit("\tstr\tw9, [sp, #4]                    ; 4-byte Folded Spill");
emit("\tcbz\tx8, LBB0_16");
emit("\tb\tLBB0_15");
emit("LBB0_15:                                ;   in Loop: Header=BB0_14 Depth=1");
emit("\tldr\tx8, [sp, #40]");
emit("\tldr\tw8, [x8]");
emit("\tldr\tw9, [sp, #68]");
emit("\tsubs\tw8, w8, w9");
emit("\tcset\tw8, lt");
emit("\tstr\tw8, [sp, #4]                    ; 4-byte Folded Spill");
emit("\tb\tLBB0_16");
emit("LBB0_16:                                ;   in Loop: Header=BB0_14 Depth=1");
emit("\tldr\tw8, [sp, #4]                    ; 4-byte Folded Reload");
emit("\ttbz\tw8, #0, LBB0_18");
emit("\tb\tLBB0_17");
emit("LBB0_17:                                ;   in Loop: Header=BB0_14 Depth=1");
emit("\tldr\tx8, [sp, #40]");
emit("\tadd\tx8, x8, #8");
emit("\tstr\tx8, [sp, #40]");
emit("\tldr\tx8, [sp, #40]");
emit("\tstr\tx8, [sp, #48]");
emit("\tldr\tx8, [sp, #40]");
emit("\tldr\tx8, [x8]");
emit("\tstr\tx8, [sp, #40]");
emit("\tb\tLBB0_14");
emit("LBB0_18:");
emit("\tldr\tx8, [sp, #40]");
emit("\tadd\tx8, x8, #8");
emit("\tstr\tx8, [sp, #24]");
emit("\tldr\tx8, [sp, #24]");
emit("\tcbnz\tx8, LBB0_22");
emit("\tb\tLBB0_19");
emit("LBB0_19:");
emit("\tldr\tw8, [sp, #68]");
emit("\tldr\tx9, [sp, #48]");
emit("\tldr\tw9, [x9]");
emit("\tsubs\tw8, w8, w9");
emit("\tb.gt\tLBB0_21");
emit("\tb\tLBB0_20");
emit("LBB0_20:");
emit("\tldr\tx8, [sp, #24]");
emit("\tstr\tx8, [sp, #56]");
emit("\tldr\tx8, [sp, #40]");
emit("\tldr\tw8, [x8]");
emit("\tstr\tw8, [sp, #20]");
emit("\tldr\tw8, [sp, #68]");
emit("\tldr\tx9, [sp, #40]");
emit("\tstr\tw8, [x9]");
emit("\tldr\tx8, [sp, #24]");
emit("\tldrsw\tx9, [sp, #68]");
emit("\tadd\tx8, x8, x9");
emit("\tldr\tx9, [sp, #24]");
emit("\tstr\tx8, [x9]");
emit("\tldr\tx8, [sp, #24]");
emit("\tldr\tx8, [x8]");
emit("\tstr\tx8, [sp, #24]");
emit("\tldr\tw8, [sp, #20]");
emit("\tldr\tw9, [sp, #68]");
emit("\tsubs\tw8, w8, w9");
emit("\tldr\tx9, [sp, #24]");
emit("\tstr\tw8, [x9]");
emit("\tldr\tx8, [sp, #56]");
emit("\tstr\tx8, [sp, #72]");
emit("\tb\tLBB0_27");
emit("LBB0_21:");
emit("                                        ; kill: def $x8 killed $xzr");
emit("\tstr\txzr, [sp, #72]");
emit("\tb\tLBB0_27");
emit("LBB0_22:");
emit("\tldr\tw8, [sp, #68]");
emit("\tldr\tx9, [sp, #48]");
emit("\tldr\tw9, [x9]");
emit("\tsubs\tw8, w8, w9");
emit("\tb.ge\tLBB0_24");
emit("\tb\tLBB0_23");
emit("LBB0_23:");
emit("\tldr\tx8, [sp, #24]");
emit("\tstr\tx8, [sp, #56]");
emit("\tldr\tx8, [sp, #40]");
emit("\tldr\tw8, [x8]");
emit("\tstr\tw8, [sp, #16]");
emit("\tldr\tw8, [sp, #68]");
emit("\tldr\tx9, [sp, #40]");
emit("\tstr\tw8, [x9]");
emit("\tldr\tx8, [sp, #40]");
emit("\tldrsw\tx9, [sp, #68]");
emit("\tadd\tx8, x8, x9");
emit("\tldr\tx9, [sp, #48]");
emit("\tstr\tx8, [x9]");
emit("\tldr\tx8, [sp, #48]");
emit("\tldr\tx8, [x8]");
emit("\tstr\tx8, [sp, #24]");
emit("\tldr\tw8, [sp, #16]");
emit("\tldr\tw9, [sp, #68]");
emit("\tsubs\tw8, w8, w9");
emit("\tldr\tx9, [sp, #24]");
emit("\tstr\tw8, [x9]");
emit("\tldr\tx8, [sp, #56]");
emit("\tstr\tx8, [sp, #72]");
emit("\tb\tLBB0_27");
emit("LBB0_24:");
emit("\tldr\tw8, [sp, #68]");
emit("\tldr\tx9, [sp, #48]");
emit("\tldr\tw9, [x9]");
emit("\tsubs\tw8, w8, w9");
emit("\tb.ne\tLBB0_26");
emit("\tb\tLBB0_25");
emit("LBB0_25:");
emit("\tldr\tx8, [sp, #24]");
emit("\tstr\tx8, [sp, #56]");
emit("\tldr\tx8, [sp, #40]");
emit("\tldrsw\tx9, [sp, #68]");
emit("\tadd\tx8, x8, x9");
emit("\tldr\tx9, [sp, #48]");
emit("\tstr\tx8, [x9]");
emit("\tldr\tx8, [sp, #56]");
emit("\tstr\tx8, [sp, #72]");
emit("\tb\tLBB0_27");
emit("LBB0_26:");
emit("                                        ; kill: def $x8 killed $xzr");
emit("\tstr\txzr, [sp, #72]");
emit("\tb\tLBB0_27");
emit("LBB0_27:");
emit("\tldr\tx0, [sp, #72]");
emit("\tadd\tsp, sp, #80");
emit("\tret");
emit("                                        ; -- End function");
emit("\t.globl\t_free_list                      ; @free_list");
emit(".zerofill __DATA,__common,_free_list,8,3");
emit(".subsections_via_symbols");
